version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: listener-net-db
    env_file:
      - .env
      - .env.dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d 
    ports:
      - "5432:5432"
    networks:
      - listener-net
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: listener-net-api
    env_file:
      - .env
      - .env.dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "8080:8080"
    networks:
      - listener-net
    depends_on:
      - db

networks:
  listener-net:
    driver: bridge

volumes:
  postgres_data: