version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: listener-net-db
    env_file:
      - .env
      - .env.dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d 
    ports:
      - "5432:5432"
    networks:
      - listener-net
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: listener-net-api
    env_file:
      - .env
      - .env.dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_HOST=localhost
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    network_mode: "host"
    command: > 
      sh -c "until pg_isready -h localhost -p ${DB_PORT} -U ${DB_USER} -d ${DB_NAME}; do
                    echo 'Waiting for db';
                    sleep 2;
                    done;
                    echo 'db is ready'
                    ./server"

networks:
  listener-net:
    driver: bridge


volumes:
  postgres_data: