-- migrations/001_init.sql

CREATE TABLE USERS (
    ID UUID PRIMARY KEY,
    IP VARCHAR(50) UNIQUE NOT NULL,
    LAST_SEEN TIMESTAMP,
    DISPOSITIVE VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE BLACKLIST (
    ID UUID PRIMARY KEY,
    IP VARCHAR(50) UNIQUE NOT NULL,
    LAST_SEEN TIMESTAMP,
    DISPOSITIVE VARCHAR(50) UNIQUE NOT NULL
);

